### ISSUE TITLE
support-rulesengine always fails to start up with go-export-client

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/support-rulesengine#26]
support-rulesengine always fails to start up with go-export-client

![image](https://user-images.githubusercontent.com/11695863/41983665-66d485b0-7a61-11e8-947a-a8c54e8fe5a2.png)

When support-rulesengine starts up, it will check the registration existence and create a new one.
However, go-export-client returns 404 Not Found when checking the registration existence, and support-rulesengine expects 200 OK with null content.
![image](https://user-images.githubusercontent.com/11695863/41983729-853400da-7a61-11e8-8720-e592b5ddb4b7.png)

It is always failed in init()
https://github.com/edgexfoundry/support-rulesengine/blob/master/src/main/java/org/edgexfoundry/export/registration/ExportClientImpl.java#L57

**Comment by cloudxxx8** [comment]
this issue is related to https://github.com/edgexfoundry/edgex-go/issues/338

**Comment by cloudxxx8** [comment]
accidentally clicked Close

**Comment by tsconn23** [comment]
@cloudxxx8 Sounds like the fix is to make the rules-engine properly handle the 404 response

**Comment by cloudxxx8** [comment]
Here is my suggested resolution

We could make the change simply in ExportClientImpl.java::isRegistered() from
```
  public boolean isRegistered() {
    return (exportRegistrationByName(clientName) != null);
  }
```
to
```
  public boolean isRegistered() {
    try {
		return (exportRegistrationByName(clientName) != null);
	} catch (NotFoundException nfE) {
		return false;
	}
  }
```
Then, it could handle the 404 response

**Comment by tsconn23** [comment]
@cloudxxx8 Yes, I think that's fine. This change will cause the rules engine to attempt to register itself (line 68) so as long as that's the intent, looks good to me.

**Comment by cloudxxx8** [comment]
@tsconn23 
please review https://github.com/edgexfoundry/support-rulesengine/pull/27 for fixing this issue
thanks
