### ISSUE TITLE
is rulesengine working currently?

### ISSUE THREAD

**Issue by ngocvantu** [edgexfoundry/support-rulesengine#5]
Hi there,
I run EdgeX using docker compose and try to use support-rulesengine to do something. I have add many rule successfully, but no rule seems to work. is rulesengine microservice working  now?
Example of my rule:
{
  "name": "humidityTooHigh5",
  "condition": {
    "device": "599562eae4b009e75b7ac4d9", // KMC.BAC-121036CE01 virtual device
    "checks": [
      {
        "parameter": "CurrentTemperature",
        "operand1": "Float.parseFloat(value)",
        "operation": ">",
        "operand2": "0"
      }
    ]
  },
  "action": {
    "device": "59944fcbe4b00e3513d8e937", // GS1-AC-Drive01 virtual device
    "command": "599562e9e4b009e75b7ac4d3",  // Status of GS1-AC-Drive01
    "body": "{\\\"collectionFrequency\\\": \\\"0002\\\"}"
  },
  "log": "warning humidity Too High"
}

**Comment by trcox** [comment]
Hi @ngocvantu, that looks pretty close! Try it with the valueDescriptor as the parameter for the condition instead of the command name. In this case, switch out "CurrentTemperature" with "AnalogInput_3000290". A command can collect multiple values, but the rules are set up to fire on a particular one.

**Comment by ngocvantu** [comment]
Still not work, Tyler !
Please take a look at my VPS: http://45.76.223.216:8080/ (virtual device)
rules : http://45.76.223.216:48075/api/v1/rule
You can do some Post to my VPS to add rules, Thanks in advanced!

**Comment by ngocvantu** [comment]
It work now, Tyler !
Solution: The first "device" will be tha name of the device, the second will be the id:
{
"name": "humidityTooHigh5",
"condition": {
"device": "KMC.BAC-121036CE01", // KMC.BAC-121036CE01 virtual device
"checks": [
{
"parameter": "CurrentTemperature",
"operand1": "Float.parseFloat(value)",
"operation": ">",
"operand2": "0"
}
]
},
"action": {
"device": "59944fcbe4b00e3513d8e937", // GS1-AC-Drive01 virtual device
"command": "599562e9e4b009e75b7ac4d3", // Status of GS1-AC-Drive01
"body": "{\"collectionFrequency\": \"0002\"}"
},
"log": "warning humidity Too High"
}

But another problem: please see the attached file, why the reading value is strange
![untitled](https://user-images.githubusercontent.com/13034353/29482801-6957d1bc-844d-11e7-9ba5-8dff4bf84d9a.png)

**Comment by trcox** [comment]
Good job fixing the first issue, I had overlooked that!

Notice that the CurrentTemperature command that you PUT to takes two parameters, collectionFrequency and enableRandomization. Your rule only specifies collectionFrequency, so it takes a default value for enableRandomization.

Try fixing your rule by making the action body: "{"collectionFrequency": "0002","enableRandomization":"true"}"
